// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using tpAPI_ASINCRO.Domain.Entities;

namespace tpAPI_ASINCRO.Repository
{
    public partial class IDBM_5Context : DbContext
    {
        public IDBM_5Context()
        {
        }

        public IDBM_5Context(DbContextOptions<IDBM_5Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Actores> Actores { get; set; }
        public virtual DbSet<Actuaciones> Actuaciones { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Actores>(entity =>
            {
                entity.HasKey(e => e.IdActor)
                    .HasName("PK__Actores__F86BE717845EE6F7");

                entity.Property(e => e.IdActor)
                    .ValueGeneratedNever()
                    .HasColumnName("id_actor");

                entity.Property(e => e.FechaNac)
                    .HasColumnType("date")
                    .HasColumnName("fecha_nac");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombre");

                entity.Property(e => e.Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("sexo")
                    .IsFixedLength();
            });

            modelBuilder.Entity<Actuaciones>(entity =>
            {
                entity.HasKey(e => e.IdActuacion)
                    .HasName("PK__Actuacio__9D2683434AC4F911");

                entity.Property(e => e.IdActuacion)
                    .ValueGeneratedNever()
                    .HasColumnName("id_actuacion");

                entity.Property(e => e.IdActor).HasColumnName("id_actor");

                entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");

                entity.Property(e => e.Papel)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("papel");

                entity.HasOne(d => d.IdActorNavigation)
                    .WithMany(p => p.Actuaciones)
                    .HasForeignKey(d => d.IdActor)
                    .HasConstraintName("FK__Actuacion__id_ac__4CA06362");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}