// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tpAPI_ASINCRO.Domain.Entities
{
    public partial class Actuaciones
    {
        public int IdActuacion { get; set; }
        public int? IdPelicula { get; set; }
        public int? IdActor { get; set; }
        public string Papel { get; set; }

        public virtual Actores IdActorNavigation { get; set; }
    }
}